### ISSUE TITLE
Set Logging Level

### ISSUE THREAD

**Issue by vale981** [thjomnx/java-systemd#2]
Thank you very much for creating this nice library!

As I am a Java noob, I haven't found a way to change the log level of the library.
Could you point that out to me?

Cheers,
Valentin

**Comment by thjomnx** [comment]
Sorry for the late response, much family overhead atm.

Currently the project is build with:

```xml
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-simple</artifactId>
  <version>1.7.5</version>
</dependency>
```

Never did this on my own and I can't actually test it due to the lack of a proper development machine, but setting the log level (once at application start!) should be possible via either `-D` property

```sh
-Dorg.slf4j.simpleLogger.defaultLogLevel=trace
```

or via configuration file `simplelogger.properties` on the classpath.

See:
- http://www.slf4j.org/manual.html
- http://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html
- https://stackoverflow.com/questions/14544991/how-to-configure-slf4j-simple

**Comment by vale981** [comment]
Thank you very much, 

Putting 

```
org.slf4j.simpleLogger.defaultLogLevel=error
```

into `simplelogger.properties` resolved the verbosity problem. 
Should this be added to the readme/wiki?

**Comment by thjomnx** [comment]
Added: https://github.com/thjomnx/java-systemd/wiki/Logging
